Add pre-build checks like `go mod tidy` and `go generate` (#2)
* Add pre-build checks

Signed-off-by: Taiki Ono <taiki@finatext.com>

* go generate ./...

Signed-off-by: Taiki Ono <taiki@finatext.com>

* Update job name

Signed-off-by: Taiki Ono <taiki@finatext.com>

* go mod tidy

Signed-off-by: Taiki Ono <taiki@finatext.com>

* Remove old golang/mock

Signed-off-by: Taiki Ono <taiki@finatext.com>

---------

Signed-off-by: Taiki Ono <taiki@finatext.com>

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -12,7 +12,6 @@ jobs:
   test:
     timeout-minutes: 10
     if: github.event.pull_request.draft == false
-    name: Run test
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -20,14 +19,67 @@ jobs:
         with:
           go-version-file: go.mod
           cache: true
-      - name: test
+      - shell: bash
         run: go test -v ./...
+
+  lint:
+    timeout-minutes: 15
+    if: github.event.pull_request.draft == false
+    name: lint
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: read
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
+        with:
+          go-version: stable
+          cache: true
+      - name: golangci-lint
+        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7.0.0
+        with:
+          only-new-issues: true
+
+  pre-build-checks:
+    timeout-minutes: 5
+    if: github.event.pull_request.draft == false
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
+        with:
+          go-version-file: go.mod
+          cache: true
+      - name: Check for go mod tidy diff
+        shell: bash
+        run: |
+          go mod tidy
+          git diff --exit-code go.mod go.sum || {
+            echo "::error::go mod tidy resulted in changes to go.mod and/or go.sum. Please run 'go mod tidy' locally and commit the changes."
+            exit 1
+          }
+      - name: Install mockgen
+        shell: bash
+        run: go install go.uber.org/mock/mockgen@latest
+      - name: Run go generate
+        shell: bash
+        run: go generate ./...
+      - name: Check for go generate diff
+        shell: bash
+        run: |
+          git diff --exit-code || {
+            echo "::error::go generate resulted in changes. Please run 'go generate ./...' locally and commit the changes."
+            exit 1
+          }
 
   build-and-release:
     timeout-minutes: 15
     if: startsWith(github.ref, 'refs/tags/v')
     needs:
       - test
+      - lint
+      - pre-build-checks
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -39,6 +91,10 @@ jobs:
         with:
           go-version-file: go.mod
           cache: true
+      - name: setup build tools
+        shell: bash
+        run: |
+          go install go.uber.org/mock/mockgen@latest
       - uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
         with:
           args: release --clean
